{% set version = "1.0.3" %}

package:
  name: podman-compose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/podman-compose/podman-compose-{{ version }}.tar.gz
  sha256: 9c9fe8249136e45257662272ade33760613e2d9ca6153269e1e970400ea14675

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - podman-compose = podman_compose:main

requirements:
  host:
    - pip
    - python >=3.5
    - python-dotenv
    - pyyaml
  run:
    - python >=3.5
    - python-dotenv
    - pyyaml

test:
  imports:
    - podman_compose
  commands:
    - pip check
    - podman-compose --help
  requires:
    - pip

about:
  home: https://github.com/containers/podman-compose
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
