{% set version = "0.1.9" %}

package:
  name: podman-compose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/podman-compose/podman-compose-{{ version }}.tar.gz
  sha256: 14c62efc92c9048eb377c7b692f555c7b988479829e02c16ff3904dcc095c640

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - podman-compose = podman_compose:main

requirements:
  host:
    - pip
    - python >=3.5
    - pyyaml
  run:
    - python >=3.5
    - pyyaml

test:
  imports:
    - podman_compose
  commands:
    - pip check
    - podman-compose --help
  requires:
    - pip

about:
  home: https://github.com/containers/podman-compose
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
