{% set version = "1.2.0" %}

package:
  name: podman-compose
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/podman-compose/podman_compose-{{ version }}.tar.gz
  sha256: e47665546598a48d83d30ca2709a679412824bbe84b93f61779bc863e1a6f060

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - podman-compose = podman_compose:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - python-dotenv
    - pyyaml

test:
  imports:
    - podman_compose
  commands:
    - pip check
    - podman-compose --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/containers/podman-compose
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
