{% set version = "1.0.6" %}

package:
  name: podman-compose
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/podman-compose/podman-compose-{{ version }}.tar.gz
  sha256: 2db235049fca50a5a4ffd511a917808c960dacb8defd5481dd8b36a77d4da2e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - podman-compose = podman_compose:main

requirements:
  host:
    - pip
    - python >=3.5
    - python-dotenv
    - pyyaml
  run:
    - python >=3.5
    - python-dotenv
    - pyyaml

test:
  imports:
    - podman_compose
  commands:
    - pip check
    - podman-compose --help
  requires:
    - pip

about:
  home: https://github.com/containers/podman-compose
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
