# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.4.1"

package:
  name: podman-compose
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/podman-compose/podman_compose-${{ version }}.tar.gz
  sha256: fc91801443cae5515ca55e72d6a961ab8524cd5483eec99230c7ac7591b841a9

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - podman-compose = podman_compose:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - python-dotenv
    - pyyaml

tests:
  - python:
      imports: podman_compose
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - podman-compose --help

about:
  summary: A script to run docker-compose.yml using podman
  license: GPL-2.0-only
  license_file: LICENSE
  homepage: https://github.com/containers/podman-compose

extra:
  recipe-maintainers:
    - bollwyvl
